version: "3"

services:
  sever:
    restart: always

    build: .
    ports:
      - "3000:3000"
    # - "9005:9005"
    volumes:
      - ".:/root/app/"
      - "node_modules_volume:/app/node_modules"
      - "yarn-cache:/usr/local/share/.cache/yarn/v6"
    tty: true
    stdin_open: true
    environment:
      - "DATABASE_PASSWORD=postgres"
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:alpine
    # ports:
    # - "5432:5432"
    volumes:
      - "data-base:/var/lib/postgres/data/"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

volumes:
  yarn-cache:
  node_modules_volume:
  data-base:
